### ISSUE TITLE
Consultation des autres user

### ISSUE THREAD

**Issue by ChaosArnhug** [Rachiid94/Projet_Dev2#11]
Il faut avoir moyen de consulter les profils des utilisateurs présent sur la BDD

**Comment by Rachiid007** [comment]
j'ai créé une fonction qui renvoie une list de tout les Users !!

**Comment by Rachiid007** [comment]
dans le fichier Users_Verification --> get_all_users() : renvoie une liste avec tous les Users !!!!!
