### ISSUE TITLE
Fonction de traitement 

### ISSUE THREAD

**Issue by ChaosArnhug** [Rachiid94/Projet_Dev2#4]
Il faut créer une fonction pour la connexion et une autre pour l'inscription depuis kivy.
Partez du principe que tout les champs sont remplis = ne gérer pas si un champs est vide
Ne faites pas de reset des champs après traitement 

Les fonctions doivent renvoyer True si la vérification passe et False dans le cas contraire

**Comment by Rachiid007** [comment]
D'accord, pour la partie connexion, je te propose la fonction is_user_in_bdd(user_name, password) : celle-ci qui devrait vérifier si l'user_name et le password existe dans la BDD.
Si c'est le cas, elle retourne True et sinon False.
