### ISSUE TITLE
Fonction de modification du profile

### ISSUE THREAD

**Issue by ChaosArnhug** [Rachiid94/Projet_Dev2#6]
il me faut une fonction pour traiter la modification du profile utilisateur.

Vous disposez de 7 champs de modifications : pseudo, email, mdp et sa confirmation, prénom, nom, age, question sécurité et sa réponse.
La fonction doit mettre à jour le profile de l'utilisateur sur les champs remplis (ils ne le sont pas forcement tous) et si ces modifications remplis les normes que l'on a fixé. De plus, les champs mdp et sa confirmation; question de sécurité et sa réponse vont de paire. Si un est remplis l'autre le doit.

**Comment by Rachiid007** [comment]
âge non modifiable (logiquement)

**Comment by ChaosArnhug** [comment]
Ducoup je mets l'age sur le register ? et je le supp de la modifictaion ?

**Comment by Rachiid007** [comment]
Bonne idée !

**Comment by ChaosArnhug** [comment]
Done

**Comment by ChaosArnhug** [comment]
Ducoup j'utilise quoi comme fonction pour update ?

**Comment by Rachiid007** [comment]
dans le fichier User_Verification.py --> update_verify
