### ISSUE TITLE
Fonction pour les rôles

### ISSUE THREAD

**Issue by ChaosArnhug** [Rachiid94/Projet_Dev2#8]
Pour le moment, la BDD me donne une liste d'id de rôle.
J'aimerais avoir une fonction qui me permet de trouver le nom de ces rôles en fonction de leur id.

**Comment by ThomasDeceuninck** [comment]
def get_role_by_name_userid(self, name, id_user): 
dans class RolesDBManagement:
fait a peu pres le meme taff nan ?

**Comment by HE201916** [comment]
Done, dans la fonction  get_roles_by_id_user
